#!/usr/bin/env python3
"""Generate 500 test queries for search evaluation."""

import json
from pathlib import Path

QUERIES_FILE = Path(__file__).parent / "fixtures" / "queries.json"

queries = []

def Q(query, intent, expected, unexpected=None, level=1, notes=""):
    queries.append({
        "query": query,
        "intent": intent,
        "level": level,
        "expected": expected,
        "unexpected": unexpected or [],
        "notes": notes,
    })

# ══════════════════════════════════════════════════════════════════════════
# Level 1: Direct Match (50 queries) — keyword exact hit
# ══════════════════════════════════════════════════════════════════════════

Q("Geoffrey Hinton", "exact", ["geoffrey-hinton"], level=1, notes="exact entity name")
Q("Yann LeCun CNN", "exact", ["yann-lecun", "convolutional-neural-network"], level=1)
Q("OpenAI GPT", "exact", ["openai", "gpt4-technical-report"], level=1)
Q("DeepMind AlphaFold", "exact", ["deepmind", "alphafold-nature-paper"], level=1)
Q("NVIDIA GPU CUDA", "exact", ["nvidia"], level=1)
Q("PyTorch framework", "exact", ["pytorch"], level=1)
Q("TensorFlow Google", "exact", ["tensorflow"], level=1)
Q("Hugging Face transformers", "exact", ["hugging-face"], level=1)
Q("Anthropic Claude", "exact", ["anthropic"], level=1)
Q("Transformer architecture", "exact", ["transformer-architecture"], level=1)
Q("backpropagation algorithm", "exact", ["backpropagation"], level=1)
Q("LSTM network", "exact", ["lstm-network"], level=1)
Q("batch normalization", "exact", ["batch-normalization"], level=1)
Q("gradient descent optimization", "exact", ["gradient-descent"], level=1)
Q("Tesla Energy Powerwall", "exact", ["tesla-energy"], level=1)
Q("CATL 宁德时代", "exact", ["catl"], level=1)
Q("ITER nuclear fusion", "exact", ["iter", "nuclear-fusion"], level=1)
Q("photovoltaic cell solar", "exact", ["photovoltaic-cell"], level=1)
Q("carbon capture storage", "exact", ["carbon-capture"], level=1)
Q("smart grid demand response", "exact", ["smart-grid"], level=1)
Q("hydrogen fuel cell", "exact", ["hydrogen-fuel-cell"], level=1)
Q("CRISPR gene editing", "exact", ["crispr-gene-editing", "crispr-therapeutics"], level=1)
Q("mRNA technology vaccine", "exact", ["mrna-technology"], level=1)
Q("CAR-T cell therapy", "exact", ["car-t-therapy"], level=1)
Q("protein folding AlphaFold", "exact", ["protein-folding", "alphafold-nature-paper"], level=1)
Q("Kubernetes container", "exact", ["kubernetes"], level=1)
Q("Docker containerization", "exact", ["docker"], level=1)
Q("microservices architecture", "exact", ["microservices"], level=1)
Q("DevOps CI/CD", "exact", ["devops"], level=1)
Q("design patterns singleton", "exact", ["design-patterns"], level=1)
Q("cold war containment", "exact", ["cold-war"], level=1)
Q("Bretton Woods system", "exact", ["bretton-woods"], level=1)
Q("globalization trade", "exact", ["globalization"], level=1)
Q("cognitive biases", "exact", ["cognitive-biases"], level=1)
Q("dual process theory Kahneman", "exact", ["dual-process-theory", "daniel-kahneman"], level=1)
Q("spaced repetition Anki", "exact", ["spaced-repetition", "anki"], level=1)
Q("quantitative trading", "exact", ["quantitative-trading"], level=1)
Q("blockchain distributed ledger", "exact", ["blockchain"], level=1)
Q("risk management VaR", "exact", ["risk-management"], level=1)
Q("behavioral economics prospect theory", "exact", ["behavioral-economics"], level=1)
Q("Zettelkasten note taking", "exact", ["zettelkasten"], level=1)
Q("Feynman technique learning", "exact", ["feynman-technique"], level=1)
Q("Bloom taxonomy", "exact", ["bloom-taxonomy"], level=1)
Q("reinforcement learning reward", "exact", ["reinforcement-learning"], level=1)
Q("GAN generative adversarial", "exact", ["generative-adversarial-network"], level=1)
Q("transfer learning fine-tuning", "exact", ["transfer-learning"], level=1)
Q("ResNet skip connection", "exact", ["resnet-paper"], level=1)
Q("BERT bidirectional transformer", "exact", ["bert-paper"], level=1)
Q("attention is all you need", "exact", ["attention-is-all-you-need"], level=1)
Q("2008 financial crisis", "exact", ["financial-crisis-2008"], level=1)

# ══════════════════════════════════════════════════════════════════════════
# Level 2: Synonym / Alternate Expression (50 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("deep learning pioneer Turing award", "conceptual", ["geoffrey-hinton"], level=2, notes="description instead of name")
Q("convolutional feature extraction image recognition", "conceptual", ["convolutional-neural-network", "imagenet-paper"], level=2, notes="concept description without saying CNN")
Q("reward-based learning policy optimization", "conceptual", ["reinforcement-learning"], level=2, notes="synonym: reinforcement learning")
Q("sequence modeling vanishing gradient gates", "conceptual", ["lstm-network"], level=2, notes="LSTM description without acronym")
Q("pre-training and fine-tuning paradigm", "conceptual", ["transfer-learning", "bert-paper"], level=2, notes="transfer learning described")
Q("generator discriminator adversarial training", "conceptual", ["generative-adversarial-network"], level=2, notes="GAN described by components")
Q("query key value self-attention", "conceptual", ["attention-mechanism", "transformer-architecture"], level=2, notes="QKV description")
Q("stochastic optimization parameter update", "conceptual", ["gradient-descent", "adam-optimizer-paper"], level=2, notes="gradient descent synonym")
Q("internal covariate shift normalization", "conceptual", ["batch-normalization"], level=2, notes="BN described by problem it solves")
Q("silicon solar energy conversion", "conceptual", ["photovoltaic-cell"], level=2, notes="PV cell described")
Q("lithium ion energy density rechargeable", "conceptual", ["battery-technology", "catl"], level=2, notes="battery described")
Q("CO2 removal atmosphere sequestration", "conceptual", ["carbon-capture"], level=2, notes="CCS described")
Q("electricity grid digital optimization IoT", "conceptual", ["smart-grid"], level=2, notes="smart grid described")
Q("水电解绿色氢气", "conceptual", ["hydrogen-fuel-cell"], level=2, notes="hydrogen fuel cell in Chinese description")
Q("托卡马克等离子体约束", "conceptual", ["nuclear-fusion", "iter"], level=2, notes="fusion described in Chinese")
Q("基因剪刀Cas9靶向编辑", "conceptual", ["crispr-gene-editing"], level=2, notes="CRISPR described in Chinese")
Q("脂质纳米颗粒疫苗递送", "conceptual", ["mrna-technology"], level=2, notes="mRNA delivery mechanism")
Q("嵌合抗原受体免疫治疗", "conceptual", ["car-t-therapy"], level=2, notes="CAR-T described in Chinese")
Q("蛋白质三维结构预测", "conceptual", ["protein-folding", "alphafold-nature-paper"], level=2, notes="protein folding described")
Q("药物靶点筛选临床前研究", "conceptual", ["drug-discovery-pipeline"], level=2, notes="drug discovery described")
Q("container orchestration pods scaling", "conceptual", ["kubernetes"], level=2, notes="K8s described")
Q("continuous integration deployment pipeline", "conceptual", ["devops", "accelerate-devops"], level=2, notes="CI/CD described")
Q("service decomposition API gateway mesh", "conceptual", ["microservices"], level=2, notes="microservices described")
Q("CAP theorem consensus algorithm", "conceptual", ["distributed-systems"], level=2, notes="distributed systems described")
Q("peer review pull request quality", "conceptual", ["code-review"], level=2, notes="code review described")
Q("red green refactor unit test first", "conceptual", ["test-driven-development"], level=2, notes="TDD described")
Q("iron curtain proxy wars mutual assured destruction", "conceptual", ["cold-war"], level=2, notes="cold war described")
Q("gold standard fixed exchange rate postwar", "conceptual", ["bretton-woods"], level=2, notes="Bretton Woods described")
Q("trade liberalization cultural exchange supply chain", "conceptual", ["globalization"], level=2, notes="globalization described")
Q("confirmation bias anchoring availability heuristic", "conceptual", ["cognitive-biases"], level=2, notes="biases listed")
Q("System 1 fast System 2 slow thinking", "conceptual", ["dual-process-theory", "thinking-fast-and-slow"], level=2, notes="dual process described")
Q("forgetting curve interval review flashcard", "conceptual", ["spaced-repetition", "anki"], level=2, notes="SRS described")
Q("algorithmic backtesting alpha generation", "conceptual", ["quantitative-trading"], level=2, notes="quant trading described")
Q("distributed ledger consensus smart contract", "conceptual", ["blockchain"], level=2, notes="blockchain described")
Q("value at risk Monte Carlo stress test", "conceptual", ["risk-management"], level=2, notes="risk mgmt described")
Q("loss aversion nudge prospect theory", "conceptual", ["behavioral-economics", "daniel-kahneman"], level=2, notes="behavioral econ described")
Q("atomic notes linking Luhmann", "conceptual", ["zettelkasten", "how-to-take-smart-notes"], level=2, notes="Zettelkasten described")
Q("teach to learn simplification explanation", "conceptual", ["feynman-technique"], level=2, notes="Feynman technique described")
Q("remember understand apply analyze evaluate create", "conceptual", ["bloom-taxonomy"], level=2, notes="Bloom levels listed")
Q("knowledge representation ontology triple extraction", "conceptual", ["knowledge-graph-methodology"], level=2, notes="KG described")
Q("海上风力发电浮式平台", "conceptual", ["offshore-wind", "wind-energy"], level=2, notes="offshore wind in Chinese")
Q("可再生能源发电成本平价", "conceptual", ["grid-parity"], level=2, notes="grid parity in Chinese")
Q("分布式小型电力系统独立运行", "conceptual", ["microgrid"], level=2, notes="microgrid in Chinese")
Q("碳排放交易体系定价", "conceptual", ["carbon-pricing"], level=2, notes="carbon pricing in Chinese")
Q("抗体偶联靶向载药", "conceptual", ["antibody-drug-conjugate"], level=2, notes="ADC in Chinese")
Q("免疫检查点T细胞激活", "conceptual", ["immunotherapy", "car-t-therapy"], level=2, notes="immunotherapy described")
Q("事件驱动消息队列异步处理", "conceptual", ["event-driven-architecture"], level=2, notes="EDA in Chinese")
Q("有界上下文聚合根领域模型", "conceptual", ["domain-driven-design"], level=2, notes="DDD in Chinese")
Q("扩散去噪图像生成", "conceptual", ["diffusion-model", "stable-diffusion"], level=2, notes="diffusion model in Chinese")
Q("tail risk fat tails uncertainty", "conceptual", ["black-swan-book", "risk-management"], level=2, notes="Black Swan concepts")

# ══════════════════════════════════════════════════════════════════════════
# Level 3: Cross-Domain Association (50 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("AI applications in drug discovery", "conceptual", ["ai-drug-discovery", "protein-folding", "drug-discovery-pipeline"], level=3, notes="ML + Bio cross-domain")
Q("machine learning for energy grid optimization", "conceptual", ["smart-grid-ml", "smart-grid", "lstm-network"], level=3, notes="ML + Energy")
Q("deep learning in quantitative finance", "conceptual", ["algorithmic-trading-ml", "quantitative-trading", "lstm-network"], level=3, notes="ML + Finance")
Q("neural network inspired by brain", "conceptual", ["neuroscience-inspired-ai", "attention-mechanism", "selective-attention"], level=3, notes="ML + CogSci")
Q("AI ethics and cognitive bias", "conceptual", ["ai-ethics", "cognitive-biases", "explainable-ai"], level=3, notes="ML + CogSci + Ethics")
Q("climate change economic impact", "conceptual", ["climate-economics", "ipcc-ar6-report", "carbon-capture"], level=3, notes="Energy + Finance")
Q("energy crisis historical context", "conceptual", ["energy-policy-history", "opec", "industrial-revolution"], level=3, notes="Energy + History")
Q("pandemic response and global health", "conceptual", ["pandemic-preparedness", "who", "covid-vaccine-development"], level=3, notes="Bio + History")
Q("open source software business model", "conceptual", ["open-source-economics", "linux-foundation", "github"], level=3, notes="SWE + Finance")
Q("online education and AI", "conceptual", ["digital-transformation-education", "khan-academy", "bloom-taxonomy"], level=3, notes="Edu + ML")
Q("AlphaFold and protein structure", "conceptual", ["alphafold-nature-paper", "protein-folding", "deepmind"], level=3, notes="ML + Bio specific")
Q("LSTM for time series prediction in energy", "conceptual", ["lstm-network", "smart-grid-ml", "smart-grid"], level=3, notes="ML technique + Energy domain")
Q("reinforcement learning in trading strategies", "conceptual", ["reinforcement-learning", "algorithmic-trading-ml", "quantitative-trading"], level=3, notes="ML technique + Finance domain")
Q("attention mechanism and human cognition", "conceptual", ["attention-mechanism", "selective-attention", "neuroscience-inspired-ai"], level=3, notes="ML concept + CogSci concept")
Q("gene editing for disease treatment", "conceptual", ["crispr-gene-editing", "gene-therapy", "crispr-therapeutics"], level=3, notes="Bio technique + Bio application")
Q("battery technology for renewable energy", "conceptual", ["battery-technology", "energy-storage", "photovoltaic-cell"], level=3, notes="Energy storage + Energy generation")
Q("distributed systems and blockchain", "conceptual", ["distributed-systems", "blockchain"], level=3, notes="SWE + Finance")
Q("DevOps and software quality", "conceptual", ["devops", "test-driven-development", "code-review"], level=3, notes="SWE practices")
Q("cognitive science and learning technology", "conceptual", ["spaced-repetition", "neuroplasticity", "digital-transformation-education"], level=3, notes="CogSci + Edu")
Q("金融危机与货币政策", "conceptual", ["financial-crisis-2008", "central-banking", "fed"], level=3, notes="Finance + History in Chinese")
Q("可持续能源投资趋势", "conceptual", ["esg-investing", "bnef-energy-transition", "climate-economics"], level=3, notes="Finance + Energy in Chinese")
Q("基因组学与精准医疗", "conceptual", ["genomics", "drug-discovery-pipeline", "illumina"], level=3, notes="Bio precision medicine")
Q("MLOps and model deployment", "conceptual", ["devops", "pytorch", "tensorflow"], level=3, notes="SWE + ML")
Q("carbon trading and ESG", "conceptual", ["carbon-pricing", "esg-investing", "climate-economics"], level=3, notes="Energy + Finance")
Q("Bretton Woods and modern monetary system", "conceptual", ["bretton-woods", "imf", "central-banking"], level=3, notes="History + Finance")
Q("RLHF and AI alignment", "conceptual", ["reinforcement-learning", "anthropic", "openai", "ai-ethics"], level=3, notes="ML + Ethics")
Q("太阳能电池材料创新", "conceptual", ["photovoltaic-cell", "nature-perovskite-review"], level=3, notes="Energy materials")
Q("认知偏差对投资决策的影响", "conceptual", ["cognitive-biases", "behavioral-economics", "risk-management"], level=3, notes="CogSci + Finance in Chinese")
Q("mRNA vaccine vs traditional vaccine safety", "conceptual", ["mrna-vs-traditional-vaccines", "mrna-technology", "covid-vaccine-development"], level=3, notes="Bio comparison")
Q("neural architecture and brain structure", "conceptual", ["neuroscience-inspired-ai", "convolutional-neural-network", "neuroplasticity"], level=3, notes="ML + CogSci deep")
Q("how does containerization help microservices", "conceptual", ["docker", "kubernetes", "microservices"], level=3, notes="SWE infrastructure")
Q("wind power forecasting with deep learning", "conceptual", ["wind-energy", "lstm-network", "smart-grid-ml"], level=3, notes="Energy + ML")
Q("immunotherapy for cancer treatment", "conceptual", ["immunotherapy", "car-t-therapy", "cancer-immunotherapy-review"], level=3, notes="Bio treatment")
Q("knowledge management tools and methods", "conceptual", ["obsidian-app", "zettelkasten", "knowledge-graph-methodology"], level=3, notes="Edu + KM")
Q("历史上的能源转型", "conceptual", ["energy-policy-history", "industrial-revolution", "opec"], level=3, notes="History + Energy in Chinese")
Q("learning science and memory", "conceptual", ["spaced-repetition", "working-memory", "make-it-stick"], level=3, notes="CogSci + Edu")
Q("federated learning for healthcare data", "conceptual", ["federated-learning", "genomics"], level=3, notes="ML + Bio privacy")
Q("explainable AI in medical diagnosis", "conceptual", ["explainable-ai", "drug-discovery-pipeline", "ai-drug-discovery"], level=3, notes="ML + Bio regulation")
Q("钙钛矿太阳能电池效率突破", "conceptual", ["nature-perovskite-review", "photovoltaic-cell"], level=3, notes="Energy materials in Chinese")
Q("国际组织与全球治理", "conceptual", ["united-nations", "imf", "world-bank", "wto"], level=3, notes="History organizations")
Q("model compression for edge deployment", "conceptual", ["model-compression", "knowledge-distillation"], level=3, notes="ML deployment")
Q("active learning strategies in education", "conceptual", ["active-recall", "feynman-technique", "bloom-taxonomy"], level=3, notes="Edu strategies")
Q("电动汽车电池供应链", "conceptual", ["catl", "battery-technology", "tesla-energy"], level=3, notes="Energy + Industry in Chinese")
Q("代码质量与技术债务", "conceptual", ["technical-debt", "code-review", "clean-architecture"], level=3, notes="SWE quality in Chinese")
Q("Obsidian PKM workflow", "conceptual", ["obsidian-app", "zettelkasten", "knowledge-graph-methodology"], level=3, notes="Edu tools")
Q("固态电池商业化前景", "conceptual", ["lithium-vs-solid-state", "battery-technology", "catl"], level=3, notes="Energy battery in Chinese")
Q("COVID-19 vaccine timeline", "conceptual", ["covid-vaccine-development", "pfizer", "moderna", "mrna-technology"], level=3, notes="Bio pandemic")
Q("graph neural network applications", "conceptual", ["convolutional-neural-network", "transformer-architecture"], level=3, notes="ML GNN")
Q("API design best practices REST GraphQL", "conceptual", ["api-design", "rest-vs-graphql", "microservices"], level=3, notes="SWE API")
Q("大模型对齐安全性", "conceptual", ["ai-ethics", "reinforcement-learning", "anthropic"], level=3, notes="ML safety in Chinese")

# ══════════════════════════════════════════════════════════════════════════
# Level 4: Disambiguation (40 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("transformer model architecture", "exact", ["transformer-architecture", "attention-is-all-you-need"], ["tesla-energy"], level=4, notes="transformer = ML, not electrical")
Q("Python deep learning", "conceptual", ["pytorch", "tensorflow"], level=4, notes="Python = programming, not snake")
Q("attention in neural networks", "conceptual", ["attention-mechanism", "transformer-architecture"], ["selective-attention"], level=4, notes="ML attention, not cognitive attention")
Q("attention in cognitive science", "conceptual", ["selective-attention", "neuroscience-inspired-ai"], ["attention-mechanism"], level=4, notes="cognitive attention, not ML attention")
Q("gates in neural networks", "conceptual", ["lstm-network"], level=4, notes="LSTM gates, not logic gates")
Q("cell in biology vs neural network", "conceptual", ["car-t-therapy", "lstm-network"], level=4, notes="biological cell vs LSTM cell")
Q("graph in knowledge management", "conceptual", ["knowledge-graph-methodology", "obsidian-app"], level=4, notes="knowledge graph, not math graph")
Q("model in machine learning", "conceptual", ["transformer-architecture", "convolutional-neural-network"], level=4, notes="ML model, not fashion model")
Q("target in drug discovery", "conceptual", ["drug-discovery-pipeline", "antibody-drug-conjugate"], level=4, notes="drug target, not business target")
Q("agent in reinforcement learning", "conceptual", ["reinforcement-learning"], level=4, notes="RL agent, not real estate agent")
Q("policy in RL vs geopolitics", "conceptual", ["reinforcement-learning"], ["energy-policy-history"], level=4, notes="RL policy, not government policy")
Q("fusion in nuclear vs data", "conceptual", ["nuclear-fusion", "iter"], level=4, notes="nuclear fusion, not data fusion")
Q("embedding in ML", "conceptual", ["transformer-architecture", "bert-paper"], level=4, notes="vector embedding, not physical embedding")
Q("network in neural vs computer", "conceptual", ["convolutional-neural-network", "lstm-network"], ["distributed-systems"], level=4, notes="neural network, not computer network")
Q("architecture in software vs neural", "conceptual", ["microservices", "clean-architecture"], level=4, notes="software architecture, not neural arch")
Q("kernel in CNN vs operating system", "conceptual", ["convolutional-neural-network"], ["linux-foundation"], level=4, notes="convolution kernel, not OS kernel")
Q("token in NLP", "conceptual", ["transformer-architecture", "attention-mechanism"], ["blockchain"], level=4, notes="NLP token, not crypto token")
Q("mining in crypto vs data", "conceptual", ["blockchain", "cryptocurrency"], level=4, notes="crypto mining")
Q("chain in blockchain vs supply chain", "conceptual", ["blockchain"], ["globalization"], level=4, notes="blockchain chain, not supply chain")
Q("learning rate in gradient descent", "conceptual", ["gradient-descent", "adam-optimizer-paper"], level=4, notes="ML parameter, not education rate")
Q("loss in neural network training", "conceptual", ["backpropagation", "gradient-descent"], ["behavioral-economics"], level=4, notes="loss function, not financial loss")
Q("bias in machine learning", "conceptual", ["convolutional-neural-network", "backpropagation"], ["cognitive-biases"], level=4, notes="ML bias term, not cognitive bias")
Q("bias in cognitive psychology", "conceptual", ["cognitive-biases", "dual-process-theory"], ["backpropagation"], level=4, notes="cognitive bias, not ML bias")
Q("container in software", "conceptual", ["docker", "kubernetes"], level=4, notes="software container, not shipping")
Q("pipeline in DevOps vs drug discovery", "conceptual", ["devops"], ["drug-discovery-pipeline"], level=4, notes="CI/CD pipeline, not drug pipeline")
Q("pipeline in drug development", "conceptual", ["drug-discovery-pipeline", "clinical-trial-phases"], ["devops"], level=4, notes="drug pipeline, not CI/CD")
Q("layer in neural network", "conceptual", ["convolutional-neural-network", "transformer-architecture"], level=4, notes="NN layer, not geological layer")
Q("weight in neural network", "conceptual", ["backpropagation", "gradient-descent"], level=4, notes="NN weight parameter")
Q("epoch in training", "conceptual", ["gradient-descent", "backpropagation"], level=4, notes="training epoch, not historical epoch")
Q("node in distributed system", "conceptual", ["distributed-systems", "kubernetes"], level=4, notes="compute node, not graph node")
Q("pool in CNN", "conceptual", ["convolutional-neural-network"], level=4, notes="pooling layer, not swimming pool")
Q("branch in git", "conceptual", ["github", "code-review"], level=4, notes="git branch, not tree branch")
Q("sprint in agile", "conceptual", ["agile-vs-waterfall", "devops"], level=4, notes="agile sprint, not running")
Q("debt in software engineering", "conceptual", ["technical-debt", "clean-architecture"], ["financial-crisis-2008"], level=4, notes="tech debt, not financial debt")
Q("bridge in knowledge graph", "conceptual", ["knowledge-graph-methodology"], level=4, notes="graph bridge node, not physical bridge")
Q("head in attention mechanism", "conceptual", ["attention-mechanism", "transformer-architecture"], level=4, notes="attention head, not human head")
Q("memory in working memory vs computer", "conceptual", ["working-memory", "metacognition"], level=4, notes="cognitive memory, not RAM")
Q("dropout in neural network", "conceptual", ["dropout-paper", "backpropagation"], level=4, notes="NN dropout, not school dropout")
Q("pruning in model compression", "conceptual", ["model-compression"], level=4, notes="model pruning, not tree pruning")
Q("distillation in knowledge transfer", "conceptual", ["knowledge-distillation", "model-compression"], level=4, notes="knowledge distillation, not chemical")

# ══════════════════════════════════════════════════════════════════════════
# Level 5: Implicit Association (50 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("how does the brain inspire computer algorithms", "exploratory", ["neuroscience-inspired-ai", "attention-mechanism", "selective-attention", "convolutional-neural-network"], level=5, notes="brain→AI, no shared keywords")
Q("what connects ancient trade routes to modern economics", "exploratory", ["silk-road", "globalization", "industrial-revolution"], level=5, notes="historical→modern connection")
Q("relationship between memory and learning efficiency", "exploratory", ["working-memory", "spaced-repetition", "neuroplasticity", "make-it-stick"], level=5, notes="cognitive→education")
Q("how do financial markets reflect human psychology", "exploratory", ["behavioral-economics", "cognitive-biases", "risk-management"], level=5, notes="finance→psychology")
Q("what role does computing power play in AI progress", "exploratory", ["nvidia", "transformer-architecture", "pytorch"], level=5, notes="hardware→AI capability")
Q("connection between climate science and investment", "exploratory", ["climate-economics", "esg-investing", "ipcc-ar6-report"], level=5, notes="science→finance")
Q("how does open source affect software innovation", "exploratory", ["open-source-economics", "linux-foundation", "github", "kubernetes"], level=5, notes="oss→innovation")
Q("parallels between biological evolution and machine learning", "exploratory", ["neural-architecture-search", "reinforcement-learning", "neuroscience-inspired-ai"], level=5, notes="biology→ML metaphor")
Q("how do economic crises reshape international institutions", "exploratory", ["financial-crisis-2008", "bretton-woods", "imf"], level=5, notes="crisis→institution")
Q("what makes effective knowledge organization", "exploratory", ["zettelkasten", "knowledge-graph-methodology", "obsidian-app", "metacognition"], level=5, notes="KM methods")
Q("energy storage and grid stability", "conceptual", ["energy-storage", "battery-technology", "smart-grid"], level=5, notes="energy infrastructure")
Q("how vaccines changed pandemic response", "conceptual", ["mrna-technology", "covid-vaccine-development", "pandemic-preparedness"], level=5, notes="vaccine→policy")
Q("学习方法与大脑可塑性的关系", "exploratory", ["neuroplasticity", "spaced-repetition", "metacognition"], level=5, notes="Chinese: learning→brain")
Q("人工智能如何改变医疗行业", "exploratory", ["ai-drug-discovery", "protein-folding", "genomics"], level=5, notes="Chinese: AI→healthcare")
Q("开源社区如何推动技术创新", "exploratory", ["open-source-economics", "linux-foundation", "github"], level=5, notes="Chinese: OSS→innovation")
Q("全球化与国际组织的演变", "exploratory", ["globalization", "united-nations", "wto", "european-union"], level=5, notes="Chinese: globalization→orgs")
Q("how does testing improve software quality", "conceptual", ["test-driven-development", "code-review", "accelerate-devops"], level=5, notes="testing→quality")
Q("relationship between monetary policy and market stability", "conceptual", ["central-banking", "fed", "financial-crisis-2008"], level=5, notes="policy→market")
Q("what makes a good research paper", "exploratory", ["attention-is-all-you-need", "resnet-paper", "bert-paper"], level=5, notes="meta: paper quality")
Q("how do international agreements affect energy policy", "exploratory", ["ipcc-ar6-report", "energy-policy-history", "climate-economics"], level=5, notes="diplomacy→energy")
Q("teacher-student relationship in knowledge transfer", "conceptual", ["knowledge-distillation", "feynman-technique", "transfer-learning"], level=5, notes="metaphor bridges ML and education")
Q("how does note-taking method affect understanding", "conceptual", ["zettelkasten", "active-recall", "metacognition", "bloom-taxonomy"], level=5, notes="PKM→cognition")
Q("information overload and decision making", "exploratory", ["cognitive-biases", "decision-fatigue", "dual-process-theory"], level=5, notes="modern problem→psychology")
Q("why do some technologies displace others", "exploratory", ["cnn-vs-transformer", "pytorch-vs-tensorflow", "lstm-vs-gru"], level=5, notes="tech evolution")
Q("how renewable energy reshapes geopolitics", "exploratory", ["energy-policy-history", "opec", "climate-economics", "photovoltaic-cell"], level=5, notes="energy→geopolitics")
Q("ethical implications of gene editing", "exploratory", ["crispr-gene-editing", "ai-ethics", "genomics"], level=5, notes="bio→ethics")
Q("数据隐私与机器学习的矛盾", "exploratory", ["federated-learning", "ai-ethics", "genomics"], level=5, notes="Chinese: privacy vs ML")
Q("从工业革命到数字革命", "exploratory", ["industrial-revolution", "globalization", "digital-transformation-education"], level=5, notes="Chinese: historical parallel")
Q("为什么深度学习需要大量计算", "exploratory", ["nvidia", "transformer-architecture", "gradient-descent", "backpropagation"], level=5, notes="Chinese: compute→DL")
Q("气候变化与公共健康", "exploratory", ["ipcc-ar6-report", "pandemic-preparedness", "who"], level=5, notes="Chinese: climate→health")
Q("知识图谱与人工智能的结合", "exploratory", ["knowledge-graph-methodology", "transformer-architecture", "ai-drug-discovery"], level=5, notes="Chinese: KG→AI")
Q("how does architecture design affect system reliability", "conceptual", ["microservices", "distributed-systems", "google-sre-book"], level=5, notes="SWE arch→reliability")
Q("biological inspiration for optimization algorithms", "conceptual", ["neural-architecture-search", "reinforcement-learning", "gradient-descent"], level=5, notes="bio→optimization")
Q("media and public perception of AI", "exploratory", ["ai-ethics", "openai", "anthropic"], level=5, notes="society→AI")
Q("how sleep affects learning and memory", "exploratory", ["neuroplasticity", "working-memory", "spaced-repetition"], level=5, notes="sleep→learning, implicit")
Q("economic inequality and globalization", "exploratory", ["globalization", "industrial-revolution", "capitalism-vs-socialism"], level=5, notes="inequality→globalization")
Q("数字货币对传统金融的冲击", "exploratory", ["cryptocurrency", "blockchain", "central-banking"], level=5, notes="Chinese: crypto→finance")
Q("科研论文的可重复性危机", "exploratory", ["clinical-trial-phases", "test-driven-development"], level=5, notes="Chinese: reproducibility")
Q("自动化对就业市场的影响", "exploratory", ["ai-ethics", "industrial-revolution", "devops"], level=5, notes="Chinese: automation→jobs")
Q("心理学如何帮助产品设计", "exploratory", ["cognitive-biases", "dual-process-theory", "design-patterns"], level=5, notes="Chinese: psychology→design")
Q("the relationship between model size and capability", "conceptual", ["transformer-architecture", "model-compression", "gpt4-technical-report"], level=5, notes="scaling laws implicit")
Q("how does peer pressure affect scientific research", "exploratory", ["code-review", "clinical-trial-phases"], level=5, notes="social→science")
Q("energy independence and national security", "exploratory", ["energy-policy-history", "opec", "nuclear-fusion"], level=5, notes="energy→security")
Q("创新生态系统的要素", "exploratory", ["open-source-economics", "silicon-road", "globalization"], level=5, notes="Chinese: innovation ecosystem")
Q("什么因素决定技术采用速度", "exploratory", ["grid-parity", "mrna-technology", "kubernetes"], level=5, notes="Chinese: adoption factors across domains")
Q("how cultural context shapes technology adoption", "exploratory", ["globalization", "digital-transformation-education", "obsidian-app"], level=5, notes="culture→tech adoption")
Q("risk perception and decision-making under uncertainty", "exploratory", ["cognitive-biases", "risk-management", "black-swan-book"], level=5, notes="psychology→risk")
Q("collaboration tools and team productivity", "exploratory", ["github", "devops", "code-review"], level=5, notes="tools→productivity")
Q("长期主义与短期利益的平衡", "exploratory", ["esg-investing", "climate-economics", "technical-debt"], level=5, notes="Chinese: long-term vs short-term across domains")
Q("how early career choices compound over time", "exploratory", ["growth-mindset", "deliberate-practice", "spaced-repetition"], level=5, notes="career→learning, very implicit")

# ══════════════════════════════════════════════════════════════════════════
# Level 6: Complex Reasoning Chain (40 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("How did Hinton's research lead to drug discovery breakthroughs", "relationship", ["geoffrey-hinton", "backpropagation", "convolutional-neural-network", "deepmind", "protein-folding", "ai-drug-discovery"], level=6, notes="hinton→backprop→deep learning→DeepMind→AlphaFold→drug discovery (4 hops)")
Q("How did cold war technology become the internet", "relationship", ["cold-war", "nato"], level=6, notes="cold war→ARPANET→internet (implicit, not fully in wiki)")
Q("How does the forgetting curve relate to AI training", "relationship", ["spaced-repetition", "neuroplasticity", "neuroscience-inspired-ai", "attention-mechanism"], level=6, notes="forgetting→memory→brain→neural network (3 hops)")
Q("连接石油危机到今天的电动汽车", "relationship", ["opec", "energy-policy-history", "photovoltaic-cell", "battery-technology", "tesla-energy"], level=6, notes="Chinese: oil crisis→energy policy→renewables→batteries→EVs (4 hops)")
Q("From ImageNet to medical diagnosis", "relationship", ["imagenet-paper", "convolutional-neural-network", "transfer-learning", "ai-drug-discovery"], level=6, notes="ImageNet→CNN→transfer learning→medical AI (3 hops)")
Q("How Kahneman's research influenced AI alignment", "relationship", ["daniel-kahneman", "cognitive-biases", "behavioral-economics", "ai-ethics", "reinforcement-learning"], level=6, notes="Kahneman→biases→behavioral econ→AI ethics→RLHF (4 hops)")
Q("Connection between gold standard and cryptocurrency", "relationship", ["bretton-woods", "central-banking", "financial-crisis-2008", "blockchain", "cryptocurrency"], level=6, notes="gold standard→central banking→crisis→blockchain→crypto (4 hops)")
Q("How brain science improved computer vision", "relationship", ["selective-attention", "neuroscience-inspired-ai", "convolutional-neural-network", "attention-mechanism"], level=6, notes="brain→neuro-AI→CNN→attention (3 hops)")
Q("从Luhmann笔记法到现代AI知识管理", "relationship", ["zettelkasten", "knowledge-graph-methodology", "obsidian-app", "transformer-architecture"], level=6, notes="Chinese: Zettelkasten→KG→Obsidian→AI (3 hops)")
Q("How battery technology connects renewable energy to electric vehicles", "relationship", ["photovoltaic-cell", "energy-storage", "battery-technology", "catl", "tesla-energy"], level=6, notes="solar→storage→batteries→CATL→Tesla (4 hops)")
Q("From human genome to personalized cancer treatment", "relationship", ["human-genome-project", "genomics", "crispr-gene-editing", "car-t-therapy"], level=6, notes="HGP→genomics→CRISPR→CAR-T (3 hops)")
Q("How open source shaped cloud computing", "relationship", ["linux-foundation", "docker", "kubernetes", "microservices"], level=6, notes="Linux→Docker→K8s→microservices (3 hops)")
Q("Link between behavioral economics and market crashes", "relationship", ["daniel-kahneman", "behavioral-economics", "cognitive-biases", "risk-management", "financial-crisis-2008"], level=6, notes="Kahneman→behav econ→biases→risk→crash (4 hops)")
Q("How transformer replaced LSTM", "relationship", ["lstm-network", "attention-mechanism", "attention-is-all-you-need", "transformer-architecture", "bert-paper"], level=6, notes="LSTM→attention→paper→transformer→BERT (4 hops)")
Q("Evolution from mainframe to serverless", "relationship", ["distributed-systems", "docker", "kubernetes", "microservices"], level=6, notes="distributed→container→K8s→serverless (3 hops)")
Q("How does education theory connect to AI", "relationship", ["bloom-taxonomy", "metacognition", "feynman-technique", "transfer-learning", "transformer-architecture"], level=6, notes="Bloom→metacognition→learning→transfer learning→transformers")
Q("气候政策如何影响能源投资", "relationship", ["ipcc-ar6-report", "carbon-pricing", "climate-economics", "esg-investing"], level=6, notes="Chinese: IPCC→carbon pricing→economics→ESG (3 hops)")
Q("从图灵奖到商业AI产品", "relationship", ["geoffrey-hinton", "backpropagation", "transformer-architecture", "openai", "gpt4-technical-report"], level=6, notes="Chinese: Hinton→backprop→transformer→OpenAI→GPT-4 (4 hops)")
Q("How CRISPR Nobel Prize connects to pharma industry", "relationship", ["crispr-nobel-lecture", "crispr-gene-editing", "crispr-therapeutics", "fda", "drug-discovery-pipeline"], level=6, notes="Nobel→CRISPR→therapeutics→FDA→drug pipeline (4 hops)")
Q("From ResNet to modern LLMs", "relationship", ["resnet-paper", "batch-normalization", "transformer-architecture", "bert-paper", "gpt4-technical-report"], level=6, notes="ResNet→BN→transformer→BERT→GPT-4 (4 hops)")
Q("How industrial revolution led to climate change discussion", "relationship", ["industrial-revolution", "globalization", "ipcc-ar6-report", "carbon-capture", "climate-economics"], level=6, notes="industry→global→IPCC→CCS→economics (4 hops)")
Q("Path from ancient trade to digital globalization", "relationship", ["silk-road", "industrial-revolution", "globalization", "blockchain"], level=6, notes="silk road→industry→globalization→digital (3 hops)")
Q("Connection between mRNA research and pandemic response", "relationship", ["mrna-technology", "pfizer", "moderna", "covid-vaccine-development", "pandemic-preparedness", "who"], level=6, notes="mRNA→pharma→vaccines→pandemic→WHO (4 hops)")
Q("从注意力机制到多模态AI", "relationship", ["attention-mechanism", "transformer-architecture", "gpt4-technical-report", "multi-modal-learning"], level=6, notes="Chinese: attention→transformer→GPT-4→multimodal (3 hops)")
Q("How software testing philosophy relates to scientific method", "relationship", ["test-driven-development", "code-review", "clinical-trial-phases"], level=6, notes="TDD→validation→scientific method (implicit)")
Q("军事技术转化为民用创新", "relationship", ["cold-war", "nato", "distributed-systems", "kubernetes"], level=6, notes="Chinese: military→civilian tech (3 hops)")
Q("From Turing Award to AI safety concerns", "relationship", ["geoffrey-hinton", "deepmind", "openai", "anthropic", "ai-ethics"], level=6, notes="Hinton→DeepMind→OpenAI→Anthropic→ethics (4 hops)")
Q("How learning science informs AI training", "relationship", ["spaced-repetition", "neuroplasticity", "neuroscience-inspired-ai", "reinforcement-learning"], level=6, notes="SRS→brain→neuro-AI→RL (3 hops)")
Q("储能技术如何推动能源转型", "relationship", ["energy-storage", "battery-technology", "smart-grid", "photovoltaic-cell", "grid-parity"], level=6, notes="Chinese: storage→battery→grid→solar→parity (4 hops)")
Q("从Adam优化器到GPT-4", "relationship", ["adam-optimizer-paper", "gradient-descent", "transformer-architecture", "openai", "gpt4-technical-report"], level=6, notes="Chinese: Adam→GD→transformer→OpenAI→GPT-4 (4 hops)")
Q("How decolonization shaped modern global institutions", "relationship", ["decolonization", "cold-war", "united-nations", "globalization"], level=6, notes="decolonization→cold war→UN→globalization (3 hops)")
Q("基因测序技术推动精准医疗", "relationship", ["illumina", "genomics", "drug-discovery-pipeline", "clinical-trial-phases"], level=6, notes="Chinese: sequencing→genomics→drug discovery→trials (3 hops)")
Q("From dropout to modern regularization", "relationship", ["dropout-paper", "batch-normalization", "transformer-architecture"], level=6, notes="dropout→BN→transformer (2 hops)")
Q("Link between Marshall Plan and EU formation", "relationship", ["marshall-plan", "cold-war", "european-union"], level=6, notes="Marshall→cold war→EU (2 hops)")
Q("How contrastive learning relates to human perception", "relationship", ["contrastive-learning", "self-supervised-learning", "selective-attention", "neuroscience-inspired-ai"], level=6, notes="CL→SSL→attention→neuro-AI (3 hops)")
Q("核聚变到无限能源的路径", "relationship", ["nuclear-fusion", "iter", "energy-storage", "smart-grid"], level=6, notes="Chinese: fusion→ITER→storage→grid (3 hops)")
Q("How few-shot learning connects to Feynman technique", "relationship", ["few-shot-learning", "transfer-learning", "feynman-technique"], level=6, notes="few-shot→transfer→Feynman (learning from few examples, 2 hops)")
Q("从布雷顿森林到加密货币", "relationship", ["bretton-woods", "central-banking", "financial-crisis-2008", "blockchain", "cryptocurrency"], level=6, notes="Chinese: BW→central bank→crisis→blockchain→crypto (4 hops)")
Q("How wind turbine design evolved with materials science", "relationship", ["wind-energy", "vestas", "siemens-gamesa", "offshore-wind"], level=6, notes="wind→manufacturers→offshore (2 hops)")
Q("Connection between working memory research and UX design", "relationship", ["working-memory", "cognitive-biases", "design-patterns"], level=6, notes="memory→biases→design (2 hops, cross CogSci+SWE)")

# ══════════════════════════════════════════════════════════════════════════
# Level 7: Mixed Language + Special Format (40 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("什么是 transformer 的 self-attention", "conceptual", ["transformer-architecture", "attention-mechanism", "attention-is-all-you-need"], level=7, notes="Chinese + English technical terms")
Q("比较 LSTM 和 GRU 的参数效率", "conceptual", ["lstm-vs-gru", "lstm-network"], level=7, notes="Chinese + English acronyms")
Q("ResNet-50 vs VGG-16 哪个更好", "conceptual", ["resnet-paper", "imagenet-paper"], level=7, notes="model names with numbers")
Q("GPT-4和Claude的区别", "conceptual", ["openai", "anthropic", "gpt4-technical-report"], level=7, notes="Chinese + product names")
Q("Adam optimizer的学习率怎么调", "conceptual", ["adam-optimizer-paper", "gradient-descent"], level=7, notes="Chinese + English optimizer name")
Q("CAR-T疗法的FDA审批流程", "conceptual", ["car-t-therapy", "fda", "clinical-trial-phases"], level=7, notes="Chinese + English acronyms")
Q("Kubernetes的pod和service区别", "conceptual", ["kubernetes", "microservices"], level=7, notes="Chinese + K8s terms")
Q("Docker和Kubernetes怎么配合", "conceptual", ["docker", "kubernetes", "devops"], level=7, notes="Chinese + product names")
Q("REST和GraphQL选哪个", "conceptual", ["rest-vs-graphql", "api-design"], level=7, notes="Chinese + API terms")
Q("SQL和NoSQL的使用场景", "conceptual", ["sql-vs-nosql", "postgresql", "distributed-systems"], level=7, notes="Chinese + DB terms")
Q("BERT vs GPT architecture differences", "conceptual", ["bert-paper", "gpt4-technical-report", "transformer-architecture"], level=7, notes="English with model names")
Q("mRNA vaccine mechanism of action", "conceptual", ["mrna-technology", "covid-vaccine-development"], level=7, notes="English medical terminology")
Q("CRISPR-Cas9 off-target effects", "conceptual", ["crispr-gene-editing"], level=7, notes="hyphenated technical term")
Q("PyTorch 2.0 vs TensorFlow 2.x", "conceptual", ["pytorch-vs-tensorflow", "pytorch", "tensorflow"], level=7, notes="version numbers")
Q("H100 GPU training performance", "conceptual", ["nvidia", "transformer-architecture"], level=7, notes="product code + technical term")
Q("PEM电解水制氢效率", "conceptual", ["hydrogen-fuel-cell"], level=7, notes="Chinese + English acronym PEM")
Q("ESG评级对投资回报的影响", "conceptual", ["esg-investing", "climate-economics"], level=7, notes="Chinese + ESG acronym")
Q("CDO和次贷危机的关系", "conceptual", ["financial-crisis-2008"], level=7, notes="Chinese + financial acronym")
Q("BM25 vs vector similarity search", "conceptual", ["knowledge-graph-methodology"], level=7, notes="search algorithm names")
Q("IoT在smart grid中的应用", "conceptual", ["smart-grid", "smart-grid-ml"], level=7, notes="English IoT + mixed")
Q("RLHF vs constitutional AI", "conceptual", ["reinforcement-learning", "anthropic", "ai-ethics"], level=7, notes="ML alignment terms")
Q("A100/H100 GPU对比", "conceptual", ["nvidia"], level=7, notes="Chinese + GPU model numbers")
Q("GAN和Diffusion Model的对比", "conceptual", ["generative-adversarial-network", "diffusion-model"], level=7, notes="Chinese + English model names")
Q("Obsidian中如何实现Zettelkasten", "conceptual", ["obsidian-app", "zettelkasten", "how-to-take-smart-notes"], level=7, notes="Chinese + product + method name")
Q("SRS算法和Anki的关系", "conceptual", ["spaced-repetition", "anki"], level=7, notes="Chinese + English acronym + product")
Q("CI/CD pipeline怎么搭建", "conceptual", ["devops", "github", "accelerate-devops"], level=7, notes="Chinese + DevOps terms")
Q("API rate limiting最佳实践", "conceptual", ["api-design"], level=7, notes="Chinese + English mixed")
Q("VaR模型的Monte Carlo方法", "conceptual", ["risk-management"], level=7, notes="Chinese + finance/math terms")
Q("Phase III clinical trial design", "conceptual", ["clinical-trial-phases"], level=7, notes="English with Roman numeral")
Q("LFP vs NMC电池技术路线", "conceptual", ["battery-technology", "catl", "lithium-vs-solid-state"], level=7, notes="Chinese + battery chemistry acronyms")
Q("PPO算法在RLHF中的应用", "conceptual", ["reinforcement-learning", "openai", "anthropic"], level=7, notes="Chinese + RL algorithm names")
Q("Istio service mesh架构", "conceptual", ["service-mesh", "microservices", "kubernetes"], level=7, notes="Chinese + product name")
Q("DAC直接空气捕获技术成本", "conceptual", ["carbon-capture"], level=7, notes="Chinese + English acronym DAC")
Q("FTS5 full-text search algorithm", "conceptual", ["knowledge-graph-methodology"], level=7, notes="SQLite search term")
Q("Q-learning vs PPO vs A3C", "conceptual", ["reinforcement-learning"], level=7, notes="multiple RL algorithm names")
Q("SimCLR对比学习框架", "conceptual", ["contrastive-learning", "self-supervised-learning"], level=7, notes="Chinese + framework name")
Q("EfficientNet和NAS的关系", "conceptual", ["neural-architecture-search", "convolutional-neural-network"], level=7, notes="Chinese + model names")
Q("GWAS全基因组关联分析", "conceptual", ["genomics", "human-genome-project"], level=7, notes="Chinese + English acronym GWAS")
Q("Markowitz投资组合优化", "conceptual", ["modern-portfolio-theory", "risk-management"], level=7, notes="Chinese + person name + theory")
Q("WTO与全球化的争议", "conceptual", ["wto", "globalization", "capitalism-vs-socialism"], level=7, notes="Chinese + English org name")

# ══════════════════════════════════════════════════════════════════════════
# Level 1 Extension: More Direct Matches (30 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("Stable Diffusion image generation", "exact", ["stable-diffusion"], level=1)
Q("Midjourney AI art", "exact", ["midjourney"], level=1)
Q("self-supervised learning", "exact", ["self-supervised-learning"], level=1)
Q("model compression techniques", "exact", ["model-compression"], level=1)
Q("federated learning privacy", "exact", ["federated-learning"], level=1)
Q("neural architecture search NAS", "exact", ["neural-architecture-search"], level=1)
Q("explainable AI XAI", "exact", ["explainable-ai"], level=1)
Q("few-shot learning meta-learning", "exact", ["few-shot-learning"], level=1)
Q("diffusion model denoising", "exact", ["diffusion-model"], level=1)
Q("knowledge distillation teacher student", "exact", ["knowledge-distillation"], level=1)
Q("contrastive learning SimCLR", "exact", ["contrastive-learning"], level=1)
Q("multi-modal learning CLIP", "exact", ["multi-modal-learning"], level=1)
Q("Roche diagnostics pharma", "exact", ["roche"], level=1)
Q("AstraZeneca oncology", "exact", ["astrazeneca"], level=1)
Q("immunotherapy checkpoint", "exact", ["immunotherapy"], level=1)
Q("gene therapy delivery", "exact", ["gene-therapy"], level=1)
Q("biomarker diagnosis", "exact", ["biomarker"], level=1)
Q("PostgreSQL database", "exact", ["postgresql"], level=1)
Q("Redis cache in-memory", "exact", ["redis"], level=1)
Q("event-driven architecture messaging", "exact", ["event-driven-architecture"], level=1)
Q("domain driven design DDD", "exact", ["domain-driven-design"], level=1)
Q("GitOps declarative", "exact", ["gitops"], level=1)
Q("WTO trade organization", "exact", ["wto"], level=1)
Q("OPEC oil cartel", "exact", ["opec"], level=1)
Q("Marshall Plan reconstruction", "exact", ["marshall-plan"], level=1)
Q("embodied cognition perception", "exact", ["embodied-cognition"], level=1)
Q("flow state optimal experience", "exact", ["flow-state"], level=1)
Q("growth mindset Dweck", "exact", ["growth-mindset"], level=1)
Q("cryptocurrency Bitcoin DeFi", "exact", ["cryptocurrency"], level=1)
Q("high frequency trading HFT", "exact", ["high-frequency-trading"], level=1)

# ══════════════════════════════════════════════════════════════════════════
# Level 2 Extension: More Synonym/Alternate (30 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("image generation from text description", "conceptual", ["stable-diffusion", "diffusion-model"], level=2, notes="text-to-image described")
Q("training with fewer labeled examples", "conceptual", ["few-shot-learning", "self-supervised-learning"], level=2, notes="few-shot described")
Q("making neural networks smaller and faster", "conceptual", ["model-compression", "knowledge-distillation"], level=2, notes="compression described")
Q("collaborative training without sharing data", "conceptual", ["federated-learning"], level=2, notes="FL described")
Q("automated neural network design", "conceptual", ["neural-architecture-search"], level=2, notes="NAS described")
Q("understanding why AI makes decisions", "conceptual", ["explainable-ai"], level=2, notes="XAI described")
Q("learning representations without labels", "conceptual", ["contrastive-learning", "self-supervised-learning"], level=2, notes="SSL/CL described")
Q("processing text images and audio together", "conceptual", ["multi-modal-learning", "gpt4-technical-report"], level=2, notes="multimodal described")
Q("小模型从大模型学习知识", "conceptual", ["knowledge-distillation", "model-compression"], level=2, notes="KD in Chinese")
Q("不需要标注数据的预训练方法", "conceptual", ["self-supervised-learning", "contrastive-learning"], level=2, notes="SSL in Chinese")
Q("让AI解释自己的推理过程", "conceptual", ["explainable-ai"], level=2, notes="XAI in Chinese")
Q("多种感官信息的联合处理", "conceptual", ["multi-modal-learning"], level=2, notes="multimodal in Chinese")
Q("去中心化数字账本技术", "conceptual", ["blockchain", "cryptocurrency"], level=2, notes="blockchain in Chinese")
Q("高速自动化证券交易", "conceptual", ["high-frequency-trading", "flash-boys"], level=2, notes="HFT in Chinese")
Q("环境社会治理投资评估", "conceptual", ["esg-investing"], level=2, notes="ESG in Chinese")
Q("关键枢纽节点的免疫疗法", "conceptual", ["immunotherapy", "car-t-therapy"], level=2, notes="immunotherapy in Chinese alt")
Q("最佳体验与沉浸感", "conceptual", ["flow-state"], level=2, notes="flow state in Chinese")
Q("固定思维与成长思维", "conceptual", ["growth-mindset"], level=2, notes="mindset in Chinese")
Q("刻意重复与专家技能", "conceptual", ["deliberate-practice", "peak-ericsson"], level=2, notes="deliberate practice in Chinese")
Q("micro power systems for remote areas", "conceptual", ["microgrid"], level=2, notes="microgrid described")
Q("clean energy cost reduction trajectory", "conceptual", ["grid-parity", "bnef-energy-transition"], level=2, notes="grid parity described")
Q("declarative infrastructure management via git", "conceptual", ["gitops", "devops"], level=2, notes="GitOps described")
Q("logging tracing metrics for services", "conceptual", ["observability", "devops"], level=2, notes="observability described")
Q("sidecar proxy for service communication", "conceptual", ["service-mesh", "microservices"], level=2, notes="service mesh described")
Q("measuring drug effectiveness in patients", "conceptual", ["biomarker", "clinical-trial-phases"], level=2, notes="biomarker described")
Q("correcting genetic mutations in living cells", "conceptual", ["gene-therapy", "crispr-gene-editing"], level=2, notes="gene therapy described")
Q("个体化基因药物反应", "conceptual", ["pharmacogenomics"], level=2, notes="pharmacogenomics in Chinese")
Q("构建主义教学方法", "conceptual", ["constructivism"], level=2, notes="constructivism in Chinese")
Q("主动检索记忆强化", "conceptual", ["active-recall", "make-it-stick"], level=2, notes="active recall in Chinese")
Q("strategic military alliance collective defense", "conceptual", ["nato", "cold-war"], level=2, notes="NATO described")

# ══════════════════════════════════════════════════════════════════════════
# Level 3 Extension: More Cross-Domain (30 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("diffusion models for molecular design", "conceptual", ["diffusion-model", "ai-drug-discovery", "drug-discovery-pipeline"], level=3, notes="ML generative + Bio")
Q("contrastive learning for medical imaging", "conceptual", ["contrastive-learning", "ai-drug-discovery"], level=3, notes="ML technique + Bio")
Q("knowledge distillation for edge deployment in IoT", "conceptual", ["knowledge-distillation", "model-compression", "smart-grid"], level=3, notes="ML + Energy IoT")
Q("federated learning for financial data privacy", "conceptual", ["federated-learning", "risk-management", "quantitative-trading"], level=3, notes="ML + Finance privacy")
Q("NAS for efficient energy forecasting models", "conceptual", ["neural-architecture-search", "smart-grid-ml", "lstm-network"], level=3, notes="ML AutoML + Energy")
Q("decision fatigue in trading", "conceptual", ["decision-fatigue", "quantitative-trading", "behavioral-economics"], level=3, notes="CogSci + Finance")
Q("growth mindset in software engineering", "conceptual", ["growth-mindset", "technical-debt", "code-review"], level=3, notes="CogSci + SWE")
Q("deliberate practice for programming skills", "conceptual", ["deliberate-practice", "test-driven-development"], level=3, notes="Edu + SWE")
Q("flow state and deep work in coding", "conceptual", ["flow-state", "code-review", "devops"], level=3, notes="CogSci + SWE")
Q("blockchain for clinical trial data integrity", "conceptual", ["blockchain", "clinical-trial-phases", "drug-discovery-pipeline"], level=3, notes="Finance tech + Bio")
Q("ESG and renewable energy investment", "conceptual", ["esg-investing", "photovoltaic-cell", "wind-energy", "bnef-energy-transition"], level=3, notes="Finance + Energy")
Q("cryptocurrency regulation and central banking", "conceptual", ["cryptocurrency", "central-banking", "fed"], level=3, notes="Finance digital + traditional")
Q("HFT algorithms using deep learning", "conceptual", ["high-frequency-trading", "lstm-network", "algorithmic-trading-ml"], level=3, notes="Finance + ML")
Q("observability in distributed ML training", "conceptual", ["observability", "distributed-systems", "pytorch"], level=3, notes="SWE + ML")
Q("GitOps for ML model deployment", "conceptual", ["gitops", "devops", "pytorch"], level=3, notes="SWE DevOps + ML")
Q("event-driven architecture for real-time analytics", "conceptual", ["event-driven-architecture", "distributed-systems", "quantitative-trading"], level=3, notes="SWE + Finance")
Q("DDD for healthcare software", "conceptual", ["domain-driven-design", "drug-discovery-pipeline"], level=3, notes="SWE + Bio")
Q("Redis caching for recommendation systems", "conceptual", ["redis", "transformer-architecture"], level=3, notes="SWE + ML")
Q("PostgreSQL for genomic data storage", "conceptual", ["postgresql", "genomics", "distributed-systems"], level=3, notes="SWE + Bio")
Q("multi-modal AI for education", "conceptual", ["multi-modal-learning", "digital-transformation-education", "bloom-taxonomy"], level=3, notes="ML + Edu")
Q("self-supervised learning for protein structure", "conceptual", ["self-supervised-learning", "protein-folding", "alphafold-nature-paper"], level=3, notes="ML + Bio")
Q("embodied cognition and robotics", "conceptual", ["embodied-cognition", "reinforcement-learning"], level=3, notes="CogSci + ML")
Q("metacognition in AI agent design", "conceptual", ["metacognition", "reinforcement-learning", "ai-ethics"], level=3, notes="CogSci + ML")
Q("Zettelkasten principles in code documentation", "conceptual", ["zettelkasten", "code-review", "technical-debt"], level=3, notes="Edu + SWE")
Q("Marshall Plan和战后经济复苏", "conceptual", ["marshall-plan", "bretton-woods", "european-union"], level=3, notes="History postwar in Chinese")
Q("核威慑与冷战军备竞赛", "conceptual", ["nuclear-deterrence", "cold-war", "nato"], level=3, notes="History military in Chinese")
Q("数字主权与AI治理", "conceptual", ["digital-sovereignty", "ai-ethics", "globalization"], level=3, notes="History + ML in Chinese")
Q("OPEC与全球能源地缘政治", "conceptual", ["opec", "energy-policy-history", "globalization"], level=3, notes="History + Energy in Chinese")
Q("微电网在农村电气化中的作用", "conceptual", ["microgrid", "photovoltaic-cell", "battery-technology"], level=3, notes="Energy rural in Chinese")
Q("碳定价对工业转型的影响", "conceptual", ["carbon-pricing", "climate-economics", "industrial-revolution"], level=3, notes="Energy + History in Chinese")

# ══════════════════════════════════════════════════════════════════════════
# Level 4 Extension: More Disambiguation (20 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("diffusion in physics vs AI", "conceptual", ["diffusion-model"], level=4, notes="diffusion model, not physical diffusion")
Q("generation in GAN vs energy", "conceptual", ["generative-adversarial-network"], ["photovoltaic-cell"], level=4, notes="image generation, not power generation")
Q("flow in psychology vs data", "conceptual", ["flow-state"], ["event-driven-architecture"], level=4, notes="flow state, not data flow")
Q("agent in AI vs financial", "conceptual", ["reinforcement-learning"], ["jpmorgan"], level=4, notes="AI agent, not financial agent")
Q("cell in battery vs biology", "conceptual", ["battery-technology", "photovoltaic-cell"], ["car-t-therapy"], level=4, notes="energy cell, not biological cell")
Q("grid in energy vs data", "conceptual", ["smart-grid"], ["distributed-systems"], level=4, notes="power grid, not data grid")
Q("protocol in blockchain vs network", "conceptual", ["blockchain"], ["distributed-systems"], level=4, notes="consensus protocol, not network protocol")
Q("exchange in crypto vs foreign", "conceptual", ["binance", "cryptocurrency"], ["bretton-woods"], level=4, notes="crypto exchange, not FX exchange")
Q("hub in network vs knowledge", "conceptual", ["distributed-systems"], level=4, notes="network hub, not knowledge hub")
Q("pruning in decision tree vs neural", "conceptual", ["model-compression"], level=4, notes="NN pruning, not tree pruning")
Q("recall in memory vs information retrieval", "conceptual", ["active-recall", "working-memory"], level=4, notes="memory recall, not IR recall")
Q("precision in medicine vs metrics", "conceptual", ["genomics", "drug-discovery-pipeline"], level=4, notes="precision medicine, not ML precision")
Q("domain in DDD vs ML", "conceptual", ["domain-driven-design"], ["transfer-learning"], level=4, notes="software domain, not ML domain")
Q("service in microservices vs cloud", "conceptual", ["microservices", "kubernetes"], level=4, notes="microservice, not cloud service")
Q("image in Docker vs computer vision", "conceptual", ["docker"], ["convolutional-neural-network"], level=4, notes="Docker image, not visual image")
Q("registry in container vs tag", "conceptual", ["docker", "kubernetes"], level=4, notes="container registry, not tag registry")
Q("volume in container vs trading", "conceptual", ["docker"], ["quantitative-trading"], level=4, notes="Docker volume, not trading volume")
Q("cluster in Kubernetes vs ML", "conceptual", ["kubernetes"], level=4, notes="K8s cluster, not data cluster")
Q("label in ML vs Kubernetes", "conceptual", ["convolutional-neural-network"], ["kubernetes"], level=4, notes="training label, not K8s label")
Q("reward in RL vs behavioral", "conceptual", ["reinforcement-learning"], ["behavioral-economics"], level=4, notes="RL reward, not economic reward")

# ══════════════════════════════════════════════════════════════════════════
# Level 5 Extension: More Implicit (30 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("why do experts make different mistakes than beginners", "exploratory", ["dual-process-theory", "cognitive-biases", "deliberate-practice"], level=5, notes="expertise→biases")
Q("how does competition drive innovation", "exploratory", ["pytorch-vs-tensorflow", "openai", "anthropic", "deepmind"], level=5, notes="market→innovation")
Q("what determines whether a technology becomes a standard", "exploratory", ["kubernetes", "docker", "transformer-architecture"], level=5, notes="standardization")
Q("how do visualization tools help understanding", "exploratory", ["obsidian-app", "knowledge-graph-methodology", "grafana"], level=5, notes="visualization→understanding")
Q("relationship between regulation and innovation speed", "exploratory", ["fda", "clinical-trial-phases", "sec", "ai-ethics"], level=5, notes="regulation→innovation tension")
Q("how does interdisciplinary thinking create breakthroughs", "exploratory", ["neuroscience-inspired-ai", "ai-drug-discovery", "behavioral-economics"], level=5, notes="cross-pollination")
Q("why do some open standards win over proprietary ones", "exploratory", ["linux-foundation", "kubernetes", "pytorch"], level=5, notes="open vs closed")
Q("how does feedback loop speed affect learning", "exploratory", ["test-driven-development", "spaced-repetition", "reinforcement-learning"], level=5, notes="feedback→learning across domains")
Q("what role does serendipity play in discovery", "exploratory", ["crispr-gene-editing", "convolutional-neural-network", "neuroscience-inspired-ai"], level=5, notes="accidental discovery")
Q("how do network effects shape technology adoption", "exploratory", ["pytorch", "kubernetes", "blockchain"], level=5, notes="network effects")
Q("人才流动如何推动技术发展", "exploratory", ["geoffrey-hinton", "google-brain", "deepmind", "openai", "anthropic"], level=5, notes="Chinese: talent flow→tech progress")
Q("标准化如何降低行业壁垒", "exploratory", ["kubernetes", "docker", "api-design"], level=5, notes="Chinese: standardization→barriers")
Q("复杂系统中的涌现行为", "exploratory", ["distributed-systems", "reinforcement-learning", "smart-grid"], level=5, notes="Chinese: emergence in complex systems")
Q("技术路线之争的决定因素", "exploratory", ["pytorch-vs-tensorflow", "lithium-vs-solid-state", "rest-vs-graphql"], level=5, notes="Chinese: tech route competition")
Q("跨学科研究的方法论", "exploratory", ["neuroscience-inspired-ai", "ai-drug-discovery", "climate-economics"], level=5, notes="Chinese: interdisciplinary methodology")
Q("how does geographic proximity affect research collaboration", "exploratory", ["google-brain", "deepmind", "openai"], level=5, notes="geography→research")
Q("what makes a framework outlast its competitors", "exploratory", ["pytorch", "tensorflow", "kubernetes"], level=5, notes="technology longevity")
Q("how do biases compound in complex systems", "exploratory", ["cognitive-biases", "risk-management", "ai-ethics"], level=5, notes="bias propagation")
Q("the cost of switching between technologies", "exploratory", ["pytorch-vs-tensorflow", "sql-vs-nosql", "agile-vs-waterfall"], level=5, notes="switching costs")
Q("how does documentation quality affect project success", "exploratory", ["code-review", "technical-debt", "zettelkasten"], level=5, notes="docs→success")
Q("简单规则产生复杂行为", "exploratory", ["reinforcement-learning", "generative-adversarial-network", "distributed-systems"], level=5, notes="Chinese: simple rules→complexity")
Q("模仿与创新的边界", "exploratory", ["transfer-learning", "generative-adversarial-network", "design-patterns"], level=5, notes="Chinese: imitation→innovation")
Q("时间压力下的决策质量", "exploratory", ["decision-fatigue", "dual-process-theory", "agile-vs-waterfall"], level=5, notes="Chinese: time pressure→decisions")
Q("信息不对称与市场效率", "exploratory", ["behavioral-economics", "quantitative-trading", "risk-management"], level=5, notes="Chinese: information asymmetry")
Q("技术民主化的双刃剑", "exploratory", ["stable-diffusion", "crispr-gene-editing", "blockchain"], level=5, notes="Chinese: democratization of tech")
Q("collaboration vs competition in scientific progress", "exploratory", ["openai", "deepmind", "anthropic", "open-source-economics"], level=5, notes="collaboration→progress")
Q("how mental models shape problem solving", "exploratory", ["dual-process-theory", "design-patterns", "metacognition"], level=5, notes="mental models")
Q("why do paradigm shifts take so long", "exploratory", ["transformer-architecture", "cnn-vs-transformer", "industrial-revolution"], level=5, notes="paradigm shifts")
Q("隐性知识的传递与管理", "exploratory", ["zettelkasten", "feynman-technique", "knowledge-distillation"], level=5, notes="Chinese: tacit knowledge across domains")
Q("技术生态系统的正反馈循环", "exploratory", ["hugging-face", "pytorch", "kubernetes", "github"], level=5, notes="Chinese: tech ecosystem feedback")

# ══════════════════════════════════════════════════════════════════════════
# Level 6 Extension: More Reasoning Chain (20 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("How did GPU gaming hardware enable AI breakthroughs", "relationship", ["nvidia", "convolutional-neural-network", "imagenet-paper", "transformer-architecture"], level=6, notes="gaming GPU→CUDA→CNN→transformers (3 hops)")
Q("From Ebbinghaus to modern AI training schedules", "relationship", ["spaced-repetition", "neuroplasticity", "neuroscience-inspired-ai", "gradient-descent"], level=6, notes="forgetting curve→brain→neuro-AI→learning rate scheduling (3 hops)")
Q("How Docker containers led to serverless computing", "relationship", ["docker", "kubernetes", "microservices", "event-driven-architecture"], level=6, notes="Docker→K8s→microservices→event-driven (3 hops)")
Q("From Luhmann's card box to AI knowledge graphs", "relationship", ["zettelkasten", "knowledge-graph-methodology", "transformer-architecture", "multi-modal-learning"], level=6, notes="cards→KG→AI→multimodal (3 hops)")
Q("How behavioral economics influenced AI alignment research", "relationship", ["behavioral-economics", "cognitive-biases", "ai-ethics", "reinforcement-learning", "anthropic"], level=6, notes="behav econ→biases→ethics→RLHF→Anthropic (4 hops)")
Q("Connection between photovoltaics and electric vehicle adoption", "relationship", ["photovoltaic-cell", "grid-parity", "energy-storage", "battery-technology", "tesla-energy"], level=6, notes="PV→parity→storage→battery→EV (4 hops)")
Q("How gene sequencing enabled mRNA vaccines", "relationship", ["illumina", "genomics", "mrna-technology", "pfizer", "covid-vaccine-development"], level=6, notes="sequencing→genomics→mRNA→Pfizer→COVID (4 hops)")
Q("从SimCLR到GPT-4的自监督学习演化", "relationship", ["contrastive-learning", "self-supervised-learning", "bert-paper", "transformer-architecture", "gpt4-technical-report"], level=6, notes="Chinese: SimCLR→SSL→BERT→transformer→GPT-4 (4 hops)")
Q("从工业革命到碳交易市场", "relationship", ["industrial-revolution", "ipcc-ar6-report", "carbon-capture", "carbon-pricing", "esg-investing"], level=6, notes="Chinese: industry→IPCC→CCS→carbon pricing→ESG (4 hops)")
Q("从人类基因组计划到个性化癌症治疗", "relationship", ["human-genome-project", "genomics", "biomarker", "car-t-therapy", "novartis"], level=6, notes="Chinese: HGP→genomics→biomarker→CAR-T→Novartis (4 hops)")
Q("How Obsidian connects to academic research workflow", "relationship", ["obsidian-app", "zettelkasten", "active-recall", "spaced-repetition", "metacognition"], level=6, notes="Obsidian→Zettel→recall→SRS→metacognition (4 hops)")
Q("From clean code to system reliability", "relationship", ["clean-architecture", "design-patterns", "technical-debt", "devops", "google-sre-book"], level=6, notes="clean arch→patterns→tech debt→DevOps→SRE (4 hops)")
Q("How OPEC shaped modern renewable energy policy", "relationship", ["opec", "oil-century", "energy-policy-history", "ipcc-ar6-report", "carbon-pricing"], level=6, notes="OPEC→oil→energy policy→IPCC→carbon pricing (4 hops)")
Q("从费曼学习法到AI教学系统", "relationship", ["feynman-technique", "bloom-taxonomy", "metacognition", "digital-transformation-education", "transformer-architecture"], level=6, notes="Chinese: Feynman→Bloom→meta→edtech→AI (4 hops)")
Q("How Redis caching connects to user experience", "relationship", ["redis", "microservices", "api-design", "distributed-systems"], level=6, notes="Redis→microservices→API→UX (3 hops)")
Q("From Markowitz to algorithmic trading", "relationship", ["modern-portfolio-theory", "risk-management", "quantitative-trading", "algorithmic-trading-ml", "lstm-network"], level=6, notes="MPT→risk→quant→ML trading→LSTM (4 hops)")
Q("去殖民化如何影响当今全球经济格局", "relationship", ["decolonization", "united-nations", "globalization", "wto", "climate-economics"], level=6, notes="Chinese: decolonization→UN→globalization→WTO→climate econ (4 hops)")
Q("从Dropout到现代大模型正则化", "relationship", ["dropout-paper", "batch-normalization", "transformer-architecture", "gpt4-technical-report"], level=6, notes="Chinese: dropout→BN→transformer→GPT-4 (3 hops)")
Q("How DDD principles improve ML system design", "relationship", ["domain-driven-design", "microservices", "devops", "pytorch"], level=6, notes="DDD→microservices→DevOps→ML deployment (3 hops)")
Q("From growth mindset to expert performance", "relationship", ["growth-mindset", "deliberate-practice", "peak-ericsson", "flow-state"], level=6, notes="mindset→practice→expertise→flow (3 hops)")

# ══════════════════════════════════════════════════════════════════════════
# Level 7 Extension: More Mixed Language (20 queries)
# ══════════════════════════════════════════════════════════════════════════

Q("Stable Diffusion和Midjourney对比", "conceptual", ["stable-diffusion", "midjourney"], level=7, notes="Chinese + product names")
Q("SimCLR vs MoCo对比学习", "conceptual", ["contrastive-learning", "self-supervised-learning"], level=7, notes="Chinese + method names")
Q("NASNet和EfficientNet的设计思路", "conceptual", ["neural-architecture-search"], level=7, notes="Chinese + model names")
Q("Grafana监控dashboard配置", "conceptual", ["grafana", "devops"], level=7, notes="Chinese + product name")
Q("Redis和PostgreSQL怎么选", "conceptual", ["redis", "postgresql", "sql-vs-nosql"], level=7, notes="Chinese + DB names")
Q("Istio vs Linkerd service mesh", "conceptual", ["service-mesh", "microservices"], level=7, notes="product comparison names")
Q("ADC抗体药物偶联物的MOA", "conceptual", ["antibody-drug-conjugate"], level=7, notes="Chinese + pharma acronyms")
Q("GWAS and precision medicine", "conceptual", ["genomics", "pharmacogenomics"], level=7, notes="English medical acronyms")
Q("DDD中的bounded context", "conceptual", ["domain-driven-design"], level=7, notes="Chinese + DDD terms")
Q("event sourcing和CQRS模式", "conceptual", ["event-driven-architecture", "design-patterns"], level=7, notes="Chinese + architecture terms")
Q("O(n²) attention complexity", "conceptual", ["attention-mechanism", "transformer-architecture"], level=7, notes="Big-O notation + technical")
Q("BTC/ETH加密资产配置", "conceptual", ["cryptocurrency", "blockchain", "binance"], level=7, notes="Chinese + crypto tickers")
Q("SDR特别提款权和IMF", "conceptual", ["imf", "bretton-woods"], level=7, notes="Chinese + financial acronym")
Q("Piaget建构主义vs Vygotsky", "conceptual", ["constructivism"], level=7, notes="Chinese + person names")
Q("Csikszentmihalyi心流理论", "conceptual", ["flow-state"], level=7, notes="Chinese + hard-to-spell name")
Q("K. Anders Ericsson刻意练习", "conceptual", ["deliberate-practice", "peak-ericsson"], level=7, notes="Chinese + person name")
Q("float16 vs bfloat16 training precision", "conceptual", ["transformer-architecture", "nvidia"], level=7, notes="data type formats")
Q("LoRA低秩适配微调", "conceptual", ["transfer-learning", "model-compression"], level=7, notes="Chinese + ML technique name")
Q("Transformer encoder-decoder vs decoder-only", "conceptual", ["transformer-architecture", "bert-paper", "gpt4-technical-report"], level=7, notes="architecture variant names")
Q("PV module degradation rate和LCOE", "conceptual", ["photovoltaic-cell", "grid-parity"], level=7, notes="Chinese + energy acronyms")

# ── Write queries ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    print(f"Generated {len(queries)} test queries")

    by_level = {}
    for q in queries:
        by_level[q["level"]] = by_level.get(q["level"], 0) + 1

    for lvl in sorted(by_level):
        labels = {1: "Direct Match", 2: "Synonym", 3: "Cross-Domain", 4: "Disambiguation", 5: "Implicit", 6: "Reasoning Chain", 7: "Mixed Language"}
        print(f"  Level {lvl} ({labels.get(lvl, '')}): {by_level[lvl]}")

    QUERIES_FILE.parent.mkdir(parents=True, exist_ok=True)
    QUERIES_FILE.write_text(json.dumps(queries, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\nWritten to: {QUERIES_FILE}")
